### ISSUE TITLE
Add support for parsing yaml configurations

### ISSUE THREAD

**Issue by FearlessHyena** [99soft/rocoto#11]
Hello, Rocoto being an extended parser I feel like it would it be great if there added support to load yaml files along with placeholder expansion and allow them to be injected like regular properties 

e.g.

```
config:
  file: sample.config
  dir: /etc/sampleApp
  path: ${dir}/${file}

# References can use the same format as Properties files
app:
  name: MyApp
  configPath: ${config.path|/etc/sampleApp/default.config}


@Inject
@Named("app.configPath")
private String appConfigPath;
```
